services:
  next:
    container_name: dsv-next
    build:
      context: ./next
      dockerfile: Dockerfile.prod
    ports:
      - "7780:3000"
    networks:
      - dsv_network

  fastapi:
    container_name: dsv-fastapi
    build:
      context: ./fastapi/main-service
      dockerfile: Dockerfile.prod
    ports:
      - "7781:8080"
    depends_on:
      - db
    volumes:
      - ./fastapi/main-service/audio-save:/app/audio-save
      - ./fastapi/main-service/tmp-audio-save:/app/tmp-audio-save
      - ./fastapi/main-service/credentials:/app/credentials
    env_file:
      - ./fastapi/main-service/app/.env
    networks:
      - dsv_network
    environment:
      PYTHONPATH: /app
      ENV: production
      MYSQL_HOST: db

  db:
    container_name: dsv-db
    build:
      context: ./mysql
      dockerfile: Dockerfile.prod
    ports:
      - "7782:3306"
    env_file:
      - ./mysql/.env
    volumes:
      - dt_live_first_release_prod:/var/lib/mysql
    networks:
      - dsv_network

  phpmyadmin:
    container_name: dsv-phpmyadmin
    image: phpmyadmin:latest
    ports:
      - "7783:80"
    environment:
      PMA_HOST: db
    networks:
      - dsv_network

volumes:
  dt_live_first_release_prod:

networks:
  dsv_network:
    external: true
