version: '3.8'

services:
  nlp_db:
    image: mysql:8.0
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: nlp
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - nlp_base:/var/lib/mysql

  adminer:
    image: adminer
    ports:
      - "7792:8080"
    depends_on:
      - nlp_db

volumes:
  nlp_base: