"""Initial migration

Revision ID: 95a1fdb1e9fd
Revises: 
Create Date: 2025-12-31 08:49:34.068887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '95a1fdb1e9fd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_adus_speech_id'), table_name='adus')
    op.create_index(op.f('ix_adus_id'), 'adus', ['id'], unique=False)
    op.create_index(op.f('ix_adus_speech_id'), 'adus', ['speech_id'], unique=False)
    op.drop_index(op.f('idx_rebuttals_src'), table_name='rebuttals')
    op.drop_index(op.f('idx_rebuttals_tgt'), table_name='rebuttals')
    op.create_index(op.f('ix_rebuttals_id'), 'rebuttals', ['id'], unique=False)
    op.create_index(op.f('ix_rebuttals_src_adu_id'), 'rebuttals', ['src_adu_id'], unique=False)
    op.create_index(op.f('ix_rebuttals_tgt_adu_id'), 'rebuttals', ['tgt_adu_id'], unique=False)
    op.alter_column('rounds', 'try_count',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('rounds', 'type',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'record'"))
    op.alter_column('rounds', 'style',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.create_index(op.f('ix_rounds_id'), 'rounds', ['id'], unique=False)
    op.create_index(op.f('ix_rounds_name'), 'rounds', ['name'], unique=False)
    op.create_index(op.f('ix_sentences_id'), 'sentences', ['id'], unique=False)
    op.create_index(op.f('ix_sentences_speech_id'), 'sentences', ['speech_id'], unique=False)
    op.alter_column('speeches', 'round_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_index(op.f('fk_speeches_round_id'), table_name='speeches')
    op.create_index(op.f('ix_speeches_id'), 'speeches', ['id'], unique=False)
    op.create_index(op.f('ix_speeches_round_id'), 'speeches', ['round_id'], unique=False)
    op.create_foreign_key(None, 'speeches', 'rounds', ['round_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_words_id'), 'words', ['id'], unique=False)
    op.create_index(op.f('ix_words_speech_id'), 'words', ['speech_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_words_speech_id'), table_name='words')
    op.drop_index(op.f('ix_words_id'), table_name='words')
    op.drop_constraint(None, 'speeches', type_='foreignkey')
    op.drop_index(op.f('ix_speeches_round_id'), table_name='speeches')
    op.drop_index(op.f('ix_speeches_id'), table_name='speeches')
    op.create_index(op.f('fk_speeches_round_id'), 'speeches', ['round_id'], unique=False)
    op.alter_column('speeches', 'round_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_sentences_speech_id'), table_name='sentences')
    op.drop_index(op.f('ix_sentences_id'), table_name='sentences')
    op.drop_index(op.f('ix_rounds_name'), table_name='rounds')
    op.drop_index(op.f('ix_rounds_id'), table_name='rounds')
    op.alter_column('rounds', 'style',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('rounds', 'type',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'record'"))
    op.alter_column('rounds', 'try_count',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    op.drop_index(op.f('ix_rebuttals_tgt_adu_id'), table_name='rebuttals')
    op.drop_index(op.f('ix_rebuttals_src_adu_id'), table_name='rebuttals')
    op.drop_index(op.f('ix_rebuttals_id'), table_name='rebuttals')
    op.create_index(op.f('idx_rebuttals_tgt'), 'rebuttals', ['tgt_adu_id'], unique=False)
    op.create_index(op.f('idx_rebuttals_src'), 'rebuttals', ['src_adu_id'], unique=False)
    op.drop_index(op.f('ix_adus_speech_id'), table_name='adus')
    op.drop_index(op.f('ix_adus_id'), table_name='adus')
    op.create_index(op.f('idx_adus_speech_id'), 'adus', ['speech_id'], unique=False)
    # ### end Alembic commands ###
