"""auto update

Revision ID: 9e2530d0f0ab
Revises: 95a1fdb1e9fd
Create Date: 2026-01-06 09:04:02.341564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e2530d0f0ab'
down_revision: Union[str, Sequence[str], None] = '95a1fdb1e9fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'speeches', 'rounds', ['round_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_words_id'), 'words', ['id'], unique=False)
    op.create_index(op.f('ix_words_speech_id'), 'words', ['speech_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_words_speech_id'), table_name='words')
    op.drop_index(op.f('ix_words_id'), table_name='words')
    op.drop_constraint(None, 'speeches', type_='foreignkey')
    # ### end Alembic commands ###
