"""Add raw_transcription to rounds table

Revision ID: 2b546eeeda57
Revises: b80c4964d100
Create Date: 2026-01-14 12:39:34.046884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b546eeeda57'
down_revision: Union[str, Sequence[str], None] = 'b80c4964d100'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rounds', sa.Column('raw_transcription', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rounds', 'raw_transcription')
    # ### end Alembic commands ###
