"""add_external_videos_table_and_refactor_rounds

Revision ID: 01180bb19f0f
Revises: dd7bb1bb6021
Create Date: 2026-01-06 11:12:43.165940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '01180bb19f0f'
down_revision: Union[str, Sequence[str], None] = 'dd7bb1bb6021'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_videos',
    sa.Column('video_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('video_id')
    )
    op.add_column('rounds', sa.Column('video_id', sa.String(length=255), nullable=True))
    op.create_foreign_key(None, 'rounds', 'external_videos', ['video_id'], ['video_id'])
    op.drop_column('rounds', 'video_source_title')
    op.drop_column('rounds', 'video_source_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rounds', sa.Column('video_source_id', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('rounds', sa.Column('video_source_title', mysql.VARCHAR(length=255), nullable=True))
    op.drop_constraint(None, 'rounds', type_='foreignkey')
    op.drop_column('rounds', 'video_id')
    op.drop_table('external_videos')
    # ### end Alembic commands ###
