"""auto update

Revision ID: d6f8beee8626
Revises: 9e2530d0f0ab
Create Date: 2026-01-06 09:04:17.037538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6f8beee8626'
down_revision: Union[str, Sequence[str], None] = '9e2530d0f0ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('fk_speeches_round_id', 'speeches', ['round_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('fk_speeches_round_id', table_name='speeches')
    # ### end Alembic commands ###
