"""update_20260106_181805

Revision ID: f7176e7e5399
Revises: d6f8beee8626
Create Date: 2026-01-06 09:18:06.192212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7176e7e5399'
down_revision: Union[str, Sequence[str], None] = 'd6f8beee8626'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rounds', sa.Column('video_source_id', sa.String(length=255), nullable=True))
    op.add_column('rounds', sa.Column('video_source_title', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rounds', 'video_source_title')
    op.drop_column('rounds', 'video_source_id')
    # ### end Alembic commands ###
