"""initial

Revision ID: a3f90e62d9da
Revises: 
Create Date: 2026-02-14 10:12:40.139261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a3f90e62d9da'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_videos',
    sa.Column('video_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('channel_id', sa.String(length=255), nullable=True),
    sa.Column('channel_title', sa.String(length=255), nullable=True),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('category_id', sa.String(length=50), nullable=True),
    sa.Column('yt_transcript', mysql.MEDIUMTEXT(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('video_id')
    )
    op.create_table('rounds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('try_count', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('style', sa.String(length=50), nullable=False),
    sa.Column('motion', sa.Text(), nullable=True),
    sa.Column('tags', sa.String(length=255), nullable=True),
    sa.Column('video_id', sa.String(length=255), nullable=True),
    sa.Column('owner_id', sa.String(length=255), nullable=True),
    sa.Column('raw_transcription', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'try_count', name='idx_rounds_name_try_count')
    )
    op.create_index(op.f('ix_rounds_id'), 'rounds', ['id'], unique=False)
    op.create_index(op.f('ix_rounds_name'), 'rounds', ['name'], unique=False)
    op.create_table('words',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=255), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_words_id'), 'words', ['id'], unique=False)
    op.create_index(op.f('ix_words_round_id'), 'words', ['round_id'], unique=False)
    op.create_table('sentences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('first_word_id', sa.Integer(), nullable=False),
    sa.Column('last_word_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['first_word_id'], ['words.id'], ),
    sa.ForeignKeyConstraint(['last_word_id'], ['words.id'], ),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sentences_id'), 'sentences', ['id'], unique=False)
    op.create_index(op.f('ix_sentences_round_id'), 'sentences', ['round_id'], unique=False)
    op.create_table('speeches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.String(length=64), nullable=False),
    sa.Column('audio_path', sa.String(length=512), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('raw_transcription', sa.JSON(), nullable=True),
    sa.Column('first_sentence_id', sa.Integer(), nullable=True),
    sa.Column('last_sentence_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['first_sentence_id'], ['sentences.id'], ),
    sa.ForeignKeyConstraint(['last_sentence_id'], ['sentences.id'], ),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('fk_speeches_round_id', 'speeches', ['round_id'], unique=False)
    op.create_index(op.f('ix_speeches_id'), 'speeches', ['id'], unique=False)
    op.create_table('adus',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('speech_id', sa.Integer(), nullable=False),
    sa.Column('first_sentence_id', sa.Integer(), nullable=False),
    sa.Column('last_sentence_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['first_sentence_id'], ['sentences.id'], ),
    sa.ForeignKeyConstraint(['last_sentence_id'], ['sentences.id'], ),
    sa.ForeignKeyConstraint(['speech_id'], ['speeches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adus_id'), 'adus', ['id'], unique=False)
    op.create_index('ix_adus_speech_id', 'adus', ['speech_id'], unique=False)
    op.create_table('rebuttals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('src_adu_id', sa.Integer(), nullable=False),
    sa.Column('tgt_adu_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['src_adu_id'], ['adus.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tgt_adu_id'], ['adus.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rebuttals_src', 'rebuttals', ['src_adu_id'], unique=False)
    op.create_index('idx_rebuttals_tgt', 'rebuttals', ['tgt_adu_id'], unique=False)
    op.create_index(op.f('ix_rebuttals_id'), 'rebuttals', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rebuttals_id'), table_name='rebuttals')
    op.drop_index('idx_rebuttals_tgt', table_name='rebuttals')
    op.drop_index('idx_rebuttals_src', table_name='rebuttals')
    op.drop_table('rebuttals')
    op.drop_index('ix_adus_speech_id', table_name='adus')
    op.drop_index(op.f('ix_adus_id'), table_name='adus')
    op.drop_table('adus')
    op.drop_index(op.f('ix_speeches_id'), table_name='speeches')
    op.drop_index('fk_speeches_round_id', table_name='speeches')
    op.drop_table('speeches')
    op.drop_index(op.f('ix_sentences_round_id'), table_name='sentences')
    op.drop_index(op.f('ix_sentences_id'), table_name='sentences')
    op.drop_table('sentences')
    op.drop_index(op.f('ix_words_round_id'), table_name='words')
    op.drop_index(op.f('ix_words_id'), table_name='words')
    op.drop_table('words')
    op.drop_index(op.f('ix_rounds_name'), table_name='rounds')
    op.drop_index(op.f('ix_rounds_id'), table_name='rounds')
    op.drop_table('rounds')
    op.drop_table('external_videos')
    # ### end Alembic commands ###
