"""update_20260117_174500

Revision ID: 9f1b2796fa9d
Revises: 4a7b9bb2e1a9
Create Date: 2026-01-17 08:45:01.706904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f1b2796fa9d'
down_revision: Union[str, Sequence[str], None] = '4a7b9bb2e1a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adus', sa.Column('start_time', sa.Float(), nullable=False))
    op.add_column('adus', sa.Column('end_time', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('adus', 'end_time')
    op.drop_column('adus', 'start_time')
    # ### end Alembic commands ###
