"""update_20260206_000635

Revision ID: 183a74939155
Revises: 9f1b2796fa9d
Create Date: 2026-02-05 15:06:37.470887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '183a74939155'
down_revision: Union[str, Sequence[str], None] = '9f1b2796fa9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rounds', sa.Column('tags', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rounds', 'tags')
    # ### end Alembic commands ###
