"""update_20260214_192108

Revision ID: 7219153ad170
Revises: a3f90e62d9da
Create Date: 2026-02-14 10:21:10.684519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7219153ad170'
down_revision: Union[str, Sequence[str], None] = 'a3f90e62d9da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rounds', sa.Column('info_slide', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rounds', 'info_slide')
    # ### end Alembic commands ###
