"""update_20260108_093538

Revision ID: b80c4964d100
Revises: f86e2f03eb88
Create Date: 2026-01-08 00:35:40.117711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b80c4964d100'
down_revision: Union[str, Sequence[str], None] = 'f86e2f03eb88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_adus_id'), 'adus', ['id'], unique=False)
    op.create_index('ix_adus_speech_id', 'adus', ['speech_id'], unique=False)
    op.create_foreign_key(None, 'adus', 'speeches', ['speech_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_rebuttals_id'), 'rebuttals', ['id'], unique=False)
    op.alter_column('rounds', 'try_count',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('rounds', 'type',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'record'"))
    op.alter_column('rounds', 'style',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.create_index(op.f('ix_rounds_id'), 'rounds', ['id'], unique=False)
    op.create_index(op.f('ix_rounds_name'), 'rounds', ['name'], unique=False)
    op.create_index(op.f('ix_sentences_id'), 'sentences', ['id'], unique=False)
    op.create_index(op.f('ix_sentences_speech_id'), 'sentences', ['speech_id'], unique=False)
    op.alter_column('speeches', 'round_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_speeches_id'), 'speeches', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_speeches_id'), table_name='speeches')
    op.alter_column('speeches', 'round_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_sentences_speech_id'), table_name='sentences')
    op.drop_index(op.f('ix_sentences_id'), table_name='sentences')
    op.drop_index(op.f('ix_rounds_name'), table_name='rounds')
    op.drop_index(op.f('ix_rounds_id'), table_name='rounds')
    op.alter_column('rounds', 'style',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('rounds', 'type',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'record'"))
    op.alter_column('rounds', 'try_count',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    op.drop_index(op.f('ix_rebuttals_id'), table_name='rebuttals')
    op.drop_constraint(None, 'adus', type_='foreignkey')
    op.drop_index('ix_adus_speech_id', table_name='adus')
    op.drop_index(op.f('ix_adus_id'), table_name='adus')
    # ### end Alembic commands ###
