"""update_20260106_203122

Revision ID: 289e84955c2e
Revises: 01180bb19f0f
Create Date: 2026-01-06 11:31:23.376995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '289e84955c2e'
down_revision: Union[str, Sequence[str], None] = '01180bb19f0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('external_videos', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('external_videos', sa.Column('published_at', sa.DateTime(), nullable=True))
    op.add_column('external_videos', sa.Column('channel_id', sa.String(length=255), nullable=True))
    op.add_column('external_videos', sa.Column('channel_title', sa.String(length=255), nullable=True))
    op.add_column('external_videos', sa.Column('tags', sa.JSON(), nullable=True))
    op.add_column('external_videos', sa.Column('category_id', sa.String(length=50), nullable=True))
    op.add_column('external_videos', sa.Column('yt_transcript', sa.Text(), nullable=True))
    op.drop_column('external_videos', 'transcript')
    op.drop_column('external_videos', 'url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('external_videos', sa.Column('url', mysql.TEXT(), nullable=True))
    op.add_column('external_videos', sa.Column('transcript', mysql.TEXT(), nullable=True))
    op.drop_column('external_videos', 'yt_transcript')
    op.drop_column('external_videos', 'category_id')
    op.drop_column('external_videos', 'tags')
    op.drop_column('external_videos', 'channel_title')
    op.drop_column('external_videos', 'channel_id')
    op.drop_column('external_videos', 'published_at')
    op.drop_column('external_videos', 'description')
    # ### end Alembic commands ###
