"""update_20260106_184237

Revision ID: dd7bb1bb6021
Revises: f7176e7e5399
Create Date: 2026-01-06 09:42:37.834219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd7bb1bb6021'
down_revision: Union[str, Sequence[str], None] = 'f7176e7e5399'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rounds', sa.Column('owner_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rounds', 'owner_id')
    # ### end Alembic commands ###
