"""update_20260106_204607

Revision ID: 19f5e5382c11
Revises: 289e84955c2e
Create Date: 2026-01-06 11:46:08.181015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19f5e5382c11'
down_revision: Union[str, Sequence[str], None] = '289e84955c2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('rounds_ibfk_1'), 'rounds', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('rounds_ibfk_1'), 'rounds', 'external_videos', ['video_id'], ['video_id'])
    # ### end Alembic commands ###
