const initialNodes = [
  { id: "g0", type: "rootNode", position: { x: 0, y: 0 }, data: { label: "Government Side" } },
  { id: "g1", type: "customNode", position: { x: 0, y: 100 }, data: { label: "こんにちはThe reason why I gave race and ethnicity as a reason why we don't implement quotas is because we think the fact that just because a certain group is oppressed and has stereotypes against them is not enough of a just reason to do so. Even if it is enough of a just reason to implement quotas, we say that the harms actually are counterintuitive and counterproductive in the liberalization of these minority groups. I'm very happy to oppose." } },
  { id: "g2", type: "customNode", position: { x: 0, y: 200 }, data: { label: "This is a debate about the individuals whom politics has forgotten." } },
  { id: "g3", type: "customNode", position: { x: 0, y: -100 }, data: { label: "What is our stance as an opposition? We say our side has a stance of trying to achieve the issue of gender equality throughout measures that are not female quotas. That looks like things like engaging in targeted recruiting and trying to increase the number of women who are capable of entering elections. We're going to promote women applying for jobs which are very male-oriented, such as getting into STEM fields. We're also going to ensure fair pay and legislative action for paid leave, for instance. We think that those cases can be done by men and don't need a radical change of female quotas which harms and infringes on the principle of equal opportunity." } },
  { id: "g4", type: "customNode", position: { x: 0, y: 500 }, data: { label: "The reason why this stance is so important but also so mutually exclusive on our house is that our side puts equal opportunity, the most fundamental case of democracy which government tried to say their side was supporting. We say that on our side, we make sure the woman with skills can go up the corporate ladder without any kind of bias, whereas in their world, they're automatically letting women into powerful positions. As a stance, we support different things, so if they try to say that all these kinds of things can be achieved on the government side, we say that's going to automatically mean their stance is contradicting because there's a difference between equal opportunity and affirmative action."} },
  { id: "o0", type: "rootNode", position: { x: 700, y: 0 }, data: { label: "Opposition Side" } },
  { id: "o1", type: "oppNode", position: { x: 700, y: 400+100 }, data: { label: "1" } },
  { id: "o2", type: "oppNode", position: { x: 700, y: 400+200 }, data: { label: "This is a debate about the individuals whom politics has forgotten." } },
  { id: "o3", type: "oppNode", position: { x: 700, y: 400+300 }, data: { label: "React+D3.jsアプリ作成の基本は React で作った DOM 要素を、D3 関数に渡してチャートを描くことです。DOM 要素を作り出すまでは React の仕事で、その DOM 要素をもらってチャート描くのは D3 の仕事です。" } },
  { id: "o4", type: "oppNode", position: { x: 700, y: 400+400 }, data: { label: "React+D3.jsアプリ作成の基本は React で作った DOM 要素を、D3 関数に渡してチャートを描くことです。DOM 要素を作り出すまでは React の仕事で、その DOM 要素をもらってチャート描くのは D3 の仕事です。" } },
];

export default initialNodes;