# ベースイメージを設定
FROM node:lts-alpine3.19

# 作業ディレクトリを設定
WORKDIR /app

# package.jsonとpackage-lock.jsonをコピー
COPY package.json package-lock.json ./

# 依存関係をインストール
RUN npm install

# アプリケーションのソースコードをコピー
COPY . .

# アプリケーションをビルド
RUN npm run build

# 環境変数を設定
ENV NODE_ENV=production

# アプリケーションの起動コマンド
CMD ["npm", "start"]